### ISSUE TITLE
error: missing_scope

### ISSUE THREAD

**Issue by lnxct** [WesleyCharlesBlake/aws-codepipeline-slack#2]
conversations.list
[ERROR]	2022-12-09T13:02:29.519Z	3148ff81-f3ec-4e5b-a265-f4feb94e34b6	error: missing_scope

**Comment by WesleyCharlesBlake** [comment]
Make sure your bot has at least the following scopes:

Your Slack App requires the following Bot Token Scopes:

channels:history
channels:manage
chat:write
chat:write.customize
chat:write.public
groups:history
links:write
